version: '3'

services:

  db:
   image: mysql:5.7
   restart: always
   environment:
#   MYSQL_ROOT: cap
#    MYSQL_PASSWORD: capwd
    MYSQL_ROOT_PASSWORD: capwd
#    MYSQL_DATABASE: database
   volumes:
   - ./mysql:/var/lib/mysql
   ports:
   - "3306:3306"

  adminer:
   image: phpmyadmin/phpmyadmin
   restart: always
   links:
   - db
   depends_on:
   - db
   ports:
   - "8081:80"

  apache:
   image: webdevops/php-apache-dev
   restart: always
   volumes:
   - .:/app
   - ./config/php.ini.default:/opt/docker/etc/php/php.ini
   ports:
   - "80:80"
   - "443:443"
   depends_on:
   - db
   links:
   - db

#docker-compose up
