#!/bin/bash
rm -rf ~/Library/Containers/com.docker.docker
rm -rf ~/.docker
rm -rf ~/goinfre/docker
mkdir -p ~/goinfre/docker/.docker
mkdir -p ~/goinfre/docker/com.docker.docker
ln -s ~/goinfre/docker/com.docker.docker ~/Library/Containers/com.docker.docker
ln -s ~/goinfre/docker/.docker ~/.docker
